### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/cynefin#2]
-wp-plugin or single app in php
-login with GR

**Comment by klokan** [comment]
I quite like Vanilla forums (vanillaforums.com). In the open-source variant it has even SSO http://docs.vanillaforums.com/features/sso/jsconnect/. Maybe worth to try...

**Comment by klokan** [comment]
Another alternative to GetSatisfaction / UserVoice (useful also for MapTiler Support Forum possibly) would be "pay once get source code": https://www.useresponse.com/

**Comment by klokan** [comment]
Another very nice: http://www.discourse.org/ (powered by Ruby On Rails - but installable easily with an official docker image.

**Comment by daliborjanak** [comment]
Pretty list of internet forum software:
https://en.wikipedia.org/wiki/Comparison_of_Internet_forum_software

**Comment by daliborjanak** [comment]
I like http://flarum.org/ based on laravel. But authentication will be bad. Vanilla looks the best (with external sso)

**Comment by klokan** [comment]
@daliborjanak - the whole forum development is confirmed by customer now.

You can start to work fulltime on the testing and deployment on production hosting as well.
Deadline on delivery is February 12th.

**Comment by daliborjanak** [comment]
It is now working on production.
