### ISSUE TITLE
Login box (information) on all wordpress pages

### ISSUE THREAD

**Issue by petrsloup** [klokantech/cynefin#3]
Add possibility to login on all pages (except the tools, where it's already present). To be integrated into the wordpress theme.

**Comment by petrsloup** [comment]
@daliborjanak This is now implemented in the master branch (https://github.com/klokantech/cynefin/commit/411b437bc60f873cdfbaf75b8d72d7a81f627b17).
Can you please test it and add to the forum header as well?

**Comment by petrsloup** [comment]
This is now done and deployed (for the wordpress pages) -- only thing left to do is to add this to the forum.

**Comment by daliborjanak** [comment]
Added to forum and deployed.
